accent = "#F43888"
cursor = "#FF4F9A"
foreground = "#F6EFF3"
background = "#1A1218"
selection_foreground = "#F6EFF3"
selection_background = "#BF0F50"

color0 = "#1A1218"
color1 = "#FF718F"
color2 = "#B4E7C7"
color3 = "#F2B86D"
color4 = "#C49BFF"
color5 = "#F43888"
color6 = "#F095C8"
color7 = "#F6EFF3"
color8 = "#342230"
color9 = "#FF4F9A"
color10 = "#B4E7C7"
color11 = "#E0C27A"
color12 = "#C49BFF"
color13 = "#FFB1DD"
color14 = "#A9C7EE"
color15 = "#F6EFF3"
